/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://egemwxfz5rb2tayfhbe6da5dca.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-p6w5ibko4zhqpgqd3zjedjmlw4",
    "aws_cognito_identity_pool_id": "us-east-1:94ec9181-e3f9-4a66-ad99-7e8d387c4612",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_W4NH3UMCi",
    "aws_user_pools_web_client_id": "8h070if6eo3rekrnnt6vs3jqg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "aws-lab-solver",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
